### Code for the GISTRE at EPITA

obj-$(CONFIG_MFRC522_EMU)        += \
	mfrc522_emu_internals.o \
	mfrc522_emu.o \
	mfrc522_emu_drv.o

# Add the directory where our builtin module is
obj-y +=
	gistre_card
