on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Coding Style + Build
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    container:
    steps:
      - uses: actions/checkout@v2
      - name: Checkpath
        run: |
          ls ./resources
          ./.github/scripts/checkpatch.sh
